### ISSUE TITLE
Troppe branch

### ISSUE THREAD

**Issue by Takeno** [leorospo/euso_react_app#4]
Guys, ci sono un po' troppe branch separate.. Cominciate ad unirle nel master e ripartire tutti dal codice condiviso

**Comment by leorospo** [comment]
Alcune sono già mergiate nel master credo.
In mattinata verifichiamo tutti insieme ed eliminiamo i rami vecchi

**Comment by leorospo** [comment]
Eliminato ramo #1 ChatList
già mergiato con commit c34fd1433ffa6923187d1b91d3959b0e4a885dad

Effettuati merge #5 (Griglia) e #6 (Login)

**Comment by leorospo** [comment]
@Takeno 
é buona norma eliminare i rami mergiati?

**Comment by Takeno** [comment]
@leorospo sì. Se fate il merge dalla PullRequest, la elimina automaticamente. Se fate merge manuale, poi dovete eliminarle manualmente da locale e da remoto.

**Comment by leorospo** [comment]
ok grazie @Takeno 
quindi i branch contrassegnati come merged li consideriamo 'chiusi', non serve eliminarli manualmente?

**Comment by Takeno** [comment]
Se li vuoi rimuovere da github, devi farlo manualmente.

**Comment by leorospo** [comment]
ok grazie
penso che li lasceremo su github

**Comment by RogiStenta** [comment]
Ciao @Takeno , pensavamo di utilizzare Realtime Database al posto di Cloud Firestore, c'è qualche motivo per cui ce lo sconsigli?

**Comment by Takeno** [comment]
Qui le differenze: https://firebase.google.com/docs/database/rtdb-vs-firestore

Sono abbastanza simili, non hanno differenze pesanti per cui scegliere specie in questa fase di studio. _Forse_ sul realtime c'è più documentazione in giro essendo più vecchio.

Sul discorso interrogazione con il database ne parleremo approfonditamente giovedì ;)

**Comment by RogiStenta** [comment]
Perfetto! Ti ringraziamo! A giovedì
